### ISSUE TITLE
Thanks for these updates

### ISSUE THREAD

**Issue by Wizard-Level-1** [TikaelSol/PF2e-Psychic-Amps#11]
Psychic is one of my favorite classes, thank you so much for keeping it up to date with this module. I guess, here's an annoying post for you to close now.

**Comment by TikaelSol** [comment]
This module is actually getting retired. We finally got amps in the system proper the other week. So update PF2e to the latest version (5.13.6) and bounce your psychic to level 0 then back up, replacing the cantrips with new copies from the system itself. The only reason I have not updated the module to send out a retirement message is that I have not finished integrating psychic dedication into the new amp stuff.
