### ISSUE TITLE
Variant spells missing for The Oscillating Wave

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [TikaelSol/PF2e-Psychic-Amps#3]
the damage differences for this subclass https://2e.aonprd.com/ConsciousMinds.aspx?ID=3 are missing for the compendium. as this subclass adds variant damage types depending on adding energy and removing energy for the spells.

**Comment by TikaelSol** [comment]
This module isn't going to be updated, it is just a stopgap until the system has better support for modifying spells.
